### PR TITLE
ADD[241]:jenkins  add example pipeline to run 2 stages in parallel

### PR DESCRIPTION
**Pull request by vivekvr1**
Closes: #241 
> *Be noted that #241  is the issue ID*

## What is the purpose of the change
To add a new pipeline script to the devops-basic repository that runs two stages in parallel.
To provide an example of how to use parallel stages in a Jenkins pipeline.
To make the devops-basic repository more comprehensive and informative.

## Add a description of the overall background and high level changes that this PR introduces

>This PR introduces a new pipeline script to the devops-basic repository called PipelineWithParallelStages.groovy.
This pipeline script runs two stages in parallel, ParallelStage1 and ParallelStage2.
Each stage simply prints a message to the console.
This pipeline script is a simple example of how to use parallel stages in a Jenkins pipeline.

### CODE REVIEW

**Comment by tungbq** [comment]
Thank you @dcompanykrish Appreciated your effort!
Similar comment with https://github.com/tungbq/devops-basic/pull/286#pullrequestreview-1633343039
In 1 PR we should only cover 1 issue. Please only change the greeting in this PR.

**Comment by dcompanykrish** [comment]
@tungbq ,Thank you for your feedback. I apologize for the inconvenience caused by my PR. I will also remove any changes that are not related to this issue. I appreciate your patience and understanding.

**Review by tungbq — CHANGES_REQUESTED** [review]
Thanks @dcompanykrish  for your understanding.
But we should not remove the file. We need to keep these files as the same with main branch but not delete them in this PR

**Comment by dcompanykrish** [comment]
Hi @tungbq ,
I understand that we should not remove the file, and I have made the necessary changes to the PR to reflect this. 🔒

Please review the changes and let me know if you have any questions or concerns. 💬

**Review by dcompanykrish — COMMENTED** [review]
I understand that we should not remove the file, and I have made the necessary changes to the PR to reflect this. 🔒

Please review the changes and let me know if you have any questions or concerns. 💬

**Review by tungbq — APPROVED** [review]
LGTM! Thanks @vivekvr1

**Pull request merged**
