### PR TITLE
 ADD[#106] : AWS-LearningResource to Extra Content table 

### PR DESCRIPTION
**Pull request by dcompanykrish**
Closes: #106 
> *Be noted that #106  is the issue ID*

Click the "Edit" button.
In the table, add a new row with the following information:
Title: AWS Learning Resource
Link: https://github.com/tungbq/AWS-LearningResource
Description: A repository of learning resources for AWS.
Click the "Commit changes" button.
>
Added AWS-LearningResource to Extra Content table
Add https://github.com/tungbq/AWS-LearningResource to this table:
https://github.com/tungbq/devops-basic#extra-content-from-other-repos

### CODE REVIEW

**Comment by tungbq** [comment]
Similar comment with https://github.com/tungbq/devops-basic/pull/286#pullrequestreview-1633343039
In 1 PR we should only cover 1 issue. Only change the related file in this PR.

**Comment by dcompanykrish** [comment]
@tungbq ,Thank you for your feedback. I apologize for the inconvenience caused by my PR. I will also remove any changes that are not related to this issue. I appreciate your patience and understanding.

**Review by tungbq — CHANGES_REQUESTED** [review]
Thanks @dcompanykrish.
But we should not remove the `topics/docker/README.md` file. We need to keep these files as the same with main branch but not delete them in this PR

**Comment by dcompanykrish** [comment]
Hi @tungbq ,
I understand that we should not remove the topics/docker/README.md file, and I have made the necessary changes to the PR to reflect this. 🔒

Please review the changes and let me know if you have any questions or concerns. 💬

**Review by dcompanykrish — COMMENTED** [review]
I understand that we should not remove the topics/docker/README.md file, and I have made the necessary changes to the PR to reflect this. 🔒

Please review the changes and let me know if you have any questions or concerns. 💬

**Review by tungbq — APPROVED** [review]
Awesome. Thank you @dcompanykrish for your contribution!

**Pull request merged**
